name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Terraform magic
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - name: Init Terraform to kick off
        run: terraform init

      - name: Plan it out
        run: terraform plan -var-file="terraform.tfvars"

      - name: Apply the damn thing
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
